name: Build

on:
  push:
    branches-ignore:
      - 'release/*.*.x' # already building package when publishing

jobs:
  publish:
    name: Build package (test)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install Node dependencies
        run: npm ci --no-audit --no-optional

      - name: Build package
        run: npm run build
