name: Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    name: Deploy example
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false # required by JamesIves/github-pages-deploy-action

      - name: Setup Node
        uses: actions/setup-node@v2.1.4
        with:
          node-version: 14

      - name: Install Node dependencies
        run: npm ci --no-audit --no-optional

      - name: Build package
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: public
          CLEAN: true
          SINGLE_COMMIT: true
