name: Publish

on:
  push:
    branches:
      - release/*

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v2.4.0

      - name: Read .nvmrc
        run: echo ::set-output name=NVMRC::$(cat .nvmrc)
        id: nvm

      - name: Setup Node (uses version from .nvmrc)
        uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ steps.nvm.outputs.NVMRC }}

      - name: Cache npm
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install Node dependencies
        run: npm ci --no-audit --no-optional

      - name: Build package
        run: npm run build

      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1.4.3
        with:
          package: ./dist/package.json
          token: ${{ secrets.NPM_TOKEN }}
